repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: local
    hooks:
      - id: smoke-test
        name: smoke test
        entry: python tests/smoke_test.py
        language: system
        pass_filenames: false
        types: [python]
