from __future__ import annotations

from pathlib import Path
from html import escape

import pandas as pd


def _fmt_number(x) -> str:
    if isinstance(x, float):
        return f"{x:.6g}"
    return str(x)


def dataframe_to_html_table(df: pd.DataFrame, max_rows: int = 20) -> str:
    if df is None or df.empty:
        return "<p><em>No rows.</em></p>"
    view = df.head(max_rows).copy()
    return view.to_html(index=False, escape=True, border=0, classes="data-table", float_format=lambda x: f"{x:.6g}")


def build_research_html_report(
    output_path: str | Path,
    title: str,
    summary: dict[str, object] | None = None,
    tables: dict[str, pd.DataFrame] | None = None,
    images: list[str | Path] | None = None,
    notes: list[str] | None = None,
) -> Path:
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary = summary or {}
    tables = tables or {}
    images = images or []
    notes = notes or []

    summary_rows = "".join(
        f"<tr><th>{escape(str(k))}</th><td>{escape(_fmt_number(v))}</td></tr>" for k, v in summary.items()
    )
    image_html = "".join(
        f'<figure><img src="{escape(str(Path(img).name))}" alt="{escape(str(Path(img).name))}"><figcaption>{escape(str(Path(img).name))}</figcaption></figure>'
        for img in images
    )
    table_html = "".join(
        f"<section><h2>{escape(name.replace('_', ' ').title())}</h2>{dataframe_to_html_table(df)}</section>"
        for name, df in tables.items()
    )
    notes_html = "".join(f"<li>{escape(n)}</li>" for n in notes)
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{escape(title)}</title>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif; margin: 32px; line-height: 1.5; color: #17202a; }}
h1 {{ margin-bottom: 0.25rem; }}
h2 {{ margin-top: 2rem; border-bottom: 1px solid #ddd; padding-bottom: 0.25rem; }}
.summary-table, .data-table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; font-size: 14px; }}
.summary-table th, .summary-table td, .data-table th, .data-table td {{ border: 1px solid #ddd; padding: 6px 8px; text-align: right; }}
.summary-table th, .data-table th {{ background: #f5f7fa; text-align: left; }}
figure {{ margin: 1rem 0; }}
img {{ max-width: 100%; border: 1px solid #ddd; }}
.note {{ background: #fff8e1; border-left: 4px solid #f0b429; padding: 12px; }}
</style>
</head>
<body>
<h1>{escape(title)}</h1>
<p>Generated by btc_quant_framework V1.2 research reporting module.</p>
<section class="note"><strong>Risk note:</strong> This report is for research and demo validation only. It is not investment advice and does not authorize live trading.</section>
<section><h2>Summary</h2><table class="summary-table">{summary_rows}</table></section>
<section><h2>Charts</h2>{image_html}</section>
<section><h2>Notes</h2><ul>{notes_html}</ul></section>
{table_html}
</body>
</html>"""
    output_path.write_text(html, encoding="utf-8")
    return output_path
